### ISSUE TITLE
Typo in key of the provided comment

### ISSUE THREAD

**Issue by fidelscodes** [learn-co-students/nested-hash-iteration-code-along-wdf-000#10]
In the example hash `contacts` in the comment at the top of the file, the keys are written as `:favorite_icecream_flavors`, but the instructions from Learn.co and the tests are using `:favorite_ice_cream_flavors`.

**Comment by paige11** [comment]
It's also written as :favorite_icecream_flavors in bin/contacts, causing the method to fail when "ruby bin/contacts" is run in the terminal.
